### ISSUE TITLE
any thoughts about build images based alpine

### ISSUE THREAD

**Issue by wanghaisheng** [confluentinc/docker-images#19]
https://github.com/gliderlabs/docker-alpine
it would be much smaller for  terrible network environment  such as China

**Comment by juyttenh** [comment]
See http://www.kingcontext.com/2016/02/06/confluent2-docker-images/#MWmKyKJ : alpine based images of 223Mb (with kafka-connect removed)

**Comment by shouze** [comment]
@juyttenh great!

ping @jcustenborder @miguno maybe https://github.com/confluentinc/docker-images/tree/master/zookeeper & https://github.com/kingcontext/docker-images/tree/master/zookeeper could be adapted/incorporated into this repo?

Today, when we use current (non alpine) docker images on our CI... the download of the kafka & zk images takes so much time comparing to our effective test run time.

**Comment by shouze** [comment]
@wanghaisheng why did you close this issue? Should be cool to make a PR on this repository instead no?
