### ISSUE TITLE
QuickStart question

### ISSUE THREAD

**Issue by vilinski** [confluentinc/docker-images#38]
Im using your quick start instructions to evaluate the confluent platform. 

- started zookeeper, 
- started kafka. 
- the problem with schema-registry: It runs without any errors, but than stops immediately. I have first overseen this, 
- started rest-proxy and got an error message about not running container. 

Have you some insights, what can be the cause for it or where to look for hidden errors? To be honest, I'm not an experienced docker user.

```
# works
# Start Zookeeper and expose port 2181 for use by the host machine
docker run -d --name zookeeper -p 2181:2181 confluent/zookeeper

# works
docker run -d --name kafka -p 9092:9092 --link zookeeper:zookeeper confluent/kafka

# doesn't run - stops without error messages
docker run -d --name schema-registry -p 8081:8081 --link zookeeper:zookeeper \
    --link kafka:kafka confluent/schema-registry

# doesn't work because linked container isn't running
docker run -d --name rest-proxy -p 8082:8082 --link zookeeper:zookeeper \
    --link kafka:kafka --link schema-registry:schema-registry confluent/rest-proxy
```

**Comment by jcustenborder** [comment]
Hi @vilinski!

Can you give the [docker-compose](https://github.com/confluentinc/docker-images#docker-compose) example a try? This might be easier to work with.

**Comment by vilinski** [comment]
Thanks, it worked. I just added http_proxy environment variables to each container in the docker-compose.yml
