### ISSUE TITLE
kafka images for windows containers

### ISSUE THREAD

**Issue by PaluruSumanth** [confluentinc/docker-images#54]
Hi,
	I want to run the below images on windows containers on windows server 2016 image as linux containers are not supported on it. do we have equivalent images which can run on windows containers for the below images.
	
	confluentinc/cp-zookeeper
	confluentinc/cp-enterprise-kafka
	confluentinc/cp-schema-registry

**Comment by rmoff** [comment]
The only images available are those published here: https://hub.docker.com/r/confluentinc.
